# Generated by Django 2.1.2 on 2018-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='donation_times',
            field=models.IntegerField(default=0),
        ),
    ]
